### ClientController Endpoints

# Get all clients (USER, ADMIN)
GET http://localhost:8080/api/clients
Content-Type: application/json
Authorization: Bearer <INSIRA O TOKEN JWT AQUI, OBTENHA NO ENDPOINT DE LOGIN>

###

# Get client by ID (USER, ADMIN)
GET http://localhost:8080/api/clients/1
Content-Type: application/json
Authorization: Bearer <INSIRA O TOKEN JWT AQUI, OBTENHA NO ENDPOINT DE LOGIN>

###

# Create a new client (ADMIN)
POST http://localhost:8080/api/clients
Content-Type: application/json
Authorization: Bearer <INSIRA O TOKEN JWT AQUI, OBTENHA NO ENDPOINT DE LOGIN>

{
  "name": "Alice Smith",
  "cpf": "12345678901",
  "gender": "FEMALE",
  "birthDate": "1990-05-12"
}

###

# Update an existing client (ADMIN)
PUT http://localhost:8080/api/clients/1
Content-Type: application/json
Authorization: Bearer <INSIRA O TOKEN JWT AQUI, OBTENHA NO ENDPOINT DE LOGIN>

{
  "name": "Alice Johnson - UPDATED",
  "cpf": "12345678901",
  "gender": "MALE"
}

###

# Delete a client (hard delete) (ADMIN)
DELETE http://localhost:8080/api/clients/1
Content-Type: application/json
Authorization: Bearer <INSIRA O TOKEN JWT AQUI, OBTENHA NO ENDPOINT DE LOGIN>

###

# Logical delete of a client (ADMIN)
DELETE http://localhost:8080/api/clients/logic-delete/2
Content-Type: application/json
Authorization: Bearer <INSIRA O TOKEN JWT AQUI, OBTENHA NO ENDPOINT DE LOGIN>

### OrderController Endpoints

# Get all orders (USER, ADMIN)
GET http://localhost:8080/api/orders
Content-Type: application/json
Authorization: Bearer <INSIRA O TOKEN JWT AQUI, OBTENHA NO ENDPOINT DE LOGIN>

###

# Get order by ID (USER, ADMIN)
GET http://localhost:8080/api/orders/1
Content-Type: application/json
Authorization: Bearer <INSIRA O TOKEN JWT AQUI, OBTENHA NO ENDPOINT DE LOGIN>

###

# Create a new order (ADMIN)
POST http://localhost:8080/api/orders
Content-Type: application/json
Authorization: Bearer <INSIRA O TOKEN JWT AQUI, OBTENHA NO ENDPOINT DE LOGIN>

{
  "codigo": "ORD123",
  "clientId": 2,
  "productsIds": [1, 2]
}

###

# Update an existing order (ADMIN)
POST http://localhost:8080/api/orders/4
Content-Type: application/json
Authorization: Bearer <INSIRA O TOKEN JWT AQUI, OBTENHA NO ENDPOINT DE LOGIN>

{
  "codigo": "ORD124 - UPDATED",
  "clientId": 2,
  "productsIds": [3, 4]
}

###

# Delete an order (hard delete) (ADMIN)
DELETE http://localhost:8080/api/orders/1
Content-Type: application/json
Authorization: Bearer <INSIRA O TOKEN JWT AQUI, OBTENHA NO ENDPOINT DE LOGIN>

###

# Logical delete of an order (ADMIN)
DELETE http://localhost:8080/api/orders/logic-delete/2
Content-Type: application/json
Authorization: Bearer <INSIRA O TOKEN JWT AQUI, OBTENHA NO ENDPOINT DE LOGIN>

###

# Add a product to an order (ADMIN)
POST http://localhost:8080/api/orders/add-product
Content-Type: application/json
Authorization: Bearer <INSIRA O TOKEN JWT AQUI, OBTENHA NO ENDPOINT DE LOGIN>

{
  "orderId": 1,
  "productId": 2
}

###

# Remove a product from an order (ADMIN)
POST http://localhost:8080/api/orders/remove-product
Content-Type: application/json
Authorization: Bearer <INSIRA O TOKEN JWT AQUI, OBTENHA NO ENDPOINT DE LOGIN>

{
  "orderId": 1,
  "productId": 2
}

### ProductController Endpoints

# Get all products (USER, ADMIN)
GET http://localhost:8080/api/products
Content-Type: application/json
Authorization: Bearer <INSIRA O TOKEN JWT AQUI, OBTENHA NO ENDPOINT DE LOGIN>

###

# Get product by ID (USER, ADMIN)
GET http://localhost:8080/api/products/9
Content-Type: application/json
Authorization: Bearer <INSIRA O TOKEN JWT AQUI, OBTENHA NO ENDPOINT DE LOGIN>

###

# Create a new product (ADMIN)
POST http://localhost:8080/api/products
Content-Type: application/json
Authorization: Bearer <INSIRA O TOKEN JWT AQUI, OBTENHA NO ENDPOINT DE LOGIN>

{
  "name": "Shampoo",
  "brand": "BrandA",
  "manufacturingDate": "2023-01-01",
  "expirationDate": "2025-01-01",
  "category": "Personal Care"
}

###

# Update an existing product (ADMIN)
PUT http://localhost:8080/api/products/1
Content-Type: application/json
Authorization: Bearer <INSIRA O TOKEN JWT AQUI, OBTENHA NO ENDPOINT DE LOGIN>

{
  "name": "Shampoo - UPDATED",
  "brand": "BrandA",
  "manufacturingDate": "2023-01-01",
  "expirationDate": "2025-01-01",
  "category": "Personal Care"
}

###

# Delete a product (hard delete) (ADMIN)
DELETE http://localhost:8080/api/products/1
Content-Type: application/json
Authorization: Bearer <INSIRA O TOKEN JWT AQUI, OBTENHA NO ENDPOINT DE LOGIN>

###

# Logical delete of a product (ADMIN)
DELETE http://localhost:8080/api/products/logic-delete/3
Content-Type: application/json
Authorization: Bearer <INSIRA O TOKEN JWT AQUI, OBTENHA NO ENDPOINT DE LOGIN>

### UserController Endpoints

# Get all users (USER, ADMIN)
GET http://localhost:8080/api/users
Content-Type: application/json
Authorization: Bearer <INSIRA O TOKEN JWT AQUI, OBTENHA NO ENDPOINT DE LOGIN>

###

# Get user by ID (USER, ADMIN)
GET http://localhost:8080/api/users/2
Content-Type: application/json
Authorization: Bearer <INSIRA O TOKEN JWT AQUI, OBTENHA NO ENDPOINT DE LOGIN>

###

# Update user password (USER, ADMIN)
POST http://localhost:8080/api/users/update-password
Content-Type: application/json
Authorization: Bearer <INSIRA O TOKEN JWT AQUI, OBTENHA NO ENDPOINT DE LOGIN>

{
  "userId": 2,
  "password": "newpassword"
}

### AuthenticationController Endpoints

# User Signup
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "username": "NewUser",
  "email": "newuser@example.com",
  "password": "password"
}

###

# User Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### UserRoleController Endpoints

# Add Role to User (ADMIN)
POST http://localhost:8080/api/add-role-to-user
Content-Type: application/json
Authorization: Bearer <INSIRA O TOKEN JWT AQUI, OBTENHA NO ENDPOINT DE LOGIN>

{
  "userId": 2,
  "role": "ROLE_ADMIN"
}